[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    X-Served-By = "netlify"

[[redirects]]
  from = "/first-aid"
  to = "https://www.jotform.com/app/253583637449470"
  status = 301

[[redirects]]
  from = "/monitoring"
  to = "https://www.jotform.com/app/253583637449470"
  status = 301

[[redirects]]
  from = "/history"
  to = "https://www.jotform.com/app/253583637449470"
  status = 301
